### ISSUE TITLE
THSegmentedControlSegments never added to self.segmentLabels

### ISSUE THREAD

**Issue by gregggreg** [tayhalla/THSegmentedControl#7]
I realize you haven't touched this code in 5 years, but thought I would log this bug anyway.

In clearExistingSeperatorsAndLabels, you go through the self.segmentLabels to remove them from their superview so that you can create new ones every time the control is re-drawn, but the problem is that the segments are never added to self.segmentLabels, so it's always empty. This results in a new set of segments being added as subviews on every redraw.

**Comment by tayhalla** [comment]
Hi @gregggreg yes - it's been a while. Thx for the note. I would love it / appreciate it if you wanted to submit a PR.

**Comment by tayhalla** [comment]
Closing with #8
